### ISSUE TITLE
Geth managed hardware wallets

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nucypher#1117]
With the release of geth 1.9.0 (see <https://blog.ethereum.org/2019/07/10/geth-v1-9-0/>) - It is no longer necessary to naively support trezor or implement its firmware libraries within nucypher if we instead depend on geth for device compadability.

Impending Changes:

- [x] Deprecate `nucypher.cli.device` (Keep `TrustedDevice` around for future feature-building) (#1052)
- [x] Remove `device` from `TransactingPower` API, revisit signing method. (#1092)
- [x] Remove `device` from `Character` APIs
- [x] Remove `device` from `CharacterConfiguration` APIs
- [x] Refactor CLI options and interactions to use geth implemented trezor support (#1056 )
~~- [ ] Web3 geth client wallet endpoint scaffolding (until web3.py adoption)~~

Included in PR #1124

**Comment by tuxxy** [comment]
What becomes of Mimosa besides `TrustedDevice`?

**Comment by KPrasch** [comment]
Reducing it to Trusted Device seems like a reasonable plan to me.

**Comment by jMyles** [comment]
A longer-term question (which, as such, perhaps doesn't belong here): how can we more closely keep our finger on the pulse of geth (and other client) development?  It's crazy to me that this was sprung upon us.  They even open the post with "After many months of silence, we’re proud to announce the v1.9.0 release of Go Ethereum!"

Surely we can peer inside the dev process occasionally to figure out what we don't know we don't know?

**Comment by cygnusv** [comment]
Off-topic: @jMyles You should look into [doxastic logic](https://en.wikipedia.org/wiki/Doxastic_logic). I think you'll like it.

**Comment by tuxxy** [comment]
#1118 was merged into `mimosa` and #1052 was merged into `master`. This accomplishes the first requirement.
