### ISSUE TITLE
Internal ANN of TACo launch

### ISSUE THREAD

**Issue by arjunhassard** [nucypher/nucypher#3186]
Should include links to: 
- [ ] Near-complete documentation for adopters https://github.com/nucypher/nucypher/issues/3142
- [ ] Complete documentation for stakers https://github.com/nucypher/nucypher/issues/3125
- [ ] Staker roundtable dates (AMA, feedback, troubleshooting) 
- [ ] Forum proposal for TACo app inclusion + bonus 
- [ ] Timeline for TACo inclusion on staker dashboard https://github.com/nucypher/tdec/issues/131
- [ ] Final early adopter list and 'prospectus' for each https://github.com/nucypher/tdec/issues/130

Additional things that should be done before ANN (but not included):

- [ ] Clarify cohort / DKG PK creation process 
- [ ] Determine timeline & viability of two types of cohort refresh (1. economical 2. emergency), including plan for cohorts to upgrade

**Comment by cygnusv** [comment]
> * Clarify cohort / DKG PK creation process

Can you extend a bit here? For the private beta phase it may be not that urgent. 

Other than that, this issue is great. Definitely our North Start for this month.

**Comment by arjunhassard** [comment]
> Can you extend a bit here? For the private beta phase it may be not that urgent.

We basically need a logistical process in place for each whitelisted DKG public key creation. So for example, an adopter jumps on a call with us and we manually generate the key, double check they've chosen the right allow logic contract, make sure their contract is now the authority, give them guidance on what they can and can't do. Something like that

**Comment by jdbertron** [comment]
Running the DKG is a manual process ?  I saw references to a script, this seems to confirm it. 
A clarification of the process is definitely needed.
